### ISSUE TITLE
Get request status

### ISSUE THREAD

**Issue by valpesendorfer** [ecmwf-projects/cads-api-client#94]
Hello,

before migrating to the new CDS platform, it was possible to check a request's status through querying `https://cds.climate.copernicus.eu/api/tasks/<id>`. After migration, this URL route returns a `404` response.

Is there any possibility to check a requests status programmatically with the new CDS?

Thanks! 

(This is related to the issue https://github.com/ecmwf/cdsapi/issues/122 and the corresponding [ECMWF forum post](https://forum.ecmwf.int/t/programatically-get-request-status-error-with-new-cdsapi/6379))

**Comment by malmans2** [comment]
Hi there,

This is supported in `cads-api-client` as follows:

```python
from cads_api_client import ApiClient

client = ApiClient()
remote = client.get_remote(request_uid)
remote.status
```

Please note that at the moment `cads-api-client` is not considered stable, and the official package recommended by ECMWF is `cdsapi`.

**Comment by valpesendorfer** [comment]
thanks @malmans2 for the quick response.

Is `cads-api-client` going to become stable and the eventual replacement for interacting with CDS? As far as I understand, the newer `cdsapi` is "wrapping" the `cads-api-client` `LegacyApiClient` - is there any chance the status could be surfaced through there to the `cdsapi`?

Thanks again

**Comment by malmans2** [comment]
> Is cads-api-client going to become stable and the eventual replacement for interacting with CDS?

Unfortunately, I'm not the right person to address this question.

> As far as I understand, the newer cdsapi is "wrapping" the cads-api-client LegacyApiClient - is there any chance the status could be surfaced through there to the cdsapi?

You are correct that there is a `LegacyApiClient` used to ensure backward compatibility with the `cdsapi.Client` methods. The reason you're unable to retrieve a job using the request ID is because you are manually instantiating the `Result` object.

If you’d like to continue using `cdsapi` exclusively, you can do the following:
```python
cdsapi_client = cdsapi.Client(...)
remote = cdsapi_client.client.get_remote(REQUEST_UID)
```
where `cdsapi_client.client` is the `cads_api_client.ApiClient` used under the hood. However, please note that also this snippet is not guaranteed to be stable.
